# Some typical dataprep commands
# Excerpted from NIST OLMEC technology
---
-   - processor
    - thread_count: 1
-   - flatten
-   - check_floorplan
    - fp_safe: 50
-   - precomp
    - wg_deep: .0225
-   - nanowire_sleeve
    - {Delta: 1.5, delta: 0.2, do_photo: true}
-   - waveguide_sleeve
    - {Delta: 2.5, delta: 0.5, do_photo: true}
-   - ground_plane
    - Delta_gp: 10.0
      points_per_circle: 80
-   - mask_map
    - mask_nw_ebeam: m2_nw_ebeam
      mask_nw_photo: m2_nw_photo
      mask_wg_ebeam: wg_full_ebeam
      mask_wg_photo: wg_full_photo
      mask_m5_wiring: m5_wiring + m5_gnd + gp_photo
-   - align_corners
...
